default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: weather_for_1_development

test:
  <<: *default
  database: weather_for_1_test

production:
  <<: *default
  database: weather_for_1_production
  username: weather_for_1
  password: <%= ENV['WEATHER_FOR_1_DATABASE_PASSWORD'] %>
